sci_fic = [
    {"Rank": 1, "Title": "Blade Runner", "Duration": "1h 57m", "Category": "AI & Cyberpunk"},
    {"Rank": 2, "Title": "2001: A Space Odyssey", "Duration": "2h 29m", "Category": "Space Exploration"},
    {"Rank": 3, "Title": "The Matrix", "Duration": "2h 16m", "Category": "Virtual Reality & AI"},
    {"Rank": 4, "Title": "Star Wars: Episode IV - A New Hope", "Duration": "2h 1m", "Category": "Space Opera"},
    {"Rank": 5, "Title": "Inception", "Duration": "2h 28m", "Category": "Dreams & Quantum Physics"},
    {"Rank": 6, "Title": "Interstellar", "Duration": "2h 49m", "Category": "Space Exploration & Time"},
    {"Rank": 7, "Title": "The Empire Strikes Back", "Duration": "2h 4m", "Category": "Space Opera"},
    {"Rank": 8, "Title": "Alien", "Duration": "1h 57m", "Category": "Alien & Survival"},
    {"Rank": 9, "Title": "Terminator 2: Judgment Day", "Duration": "2h 17m", "Category": "AI & Time Travel"},
    {"Rank": 10, "Title": "E.T. the Extra-Terrestrial", "Duration": "1h 55m", "Category": "Alien & Family"},
    {"Rank": 11, "Title": "Jurassic Park", "Duration": "2h 7m", "Category": "Genetics & Dinosaurs"},
    {"Rank": 12, "Title": "The Day the Earth Stood Still", "Duration": "1h 32m", "Category": "Alien & Peace"},
    {"Rank": 13, "Title": "Arrival", "Duration": "1h 56m", "Category": "Alien & Language"},
    {"Rank": 14, "Title": "Gravity", "Duration": "1h 31m", "Category": "Space Survival"},
    {"Rank": 15, "Title": "The Fifth Element", "Duration": "2h 6m", "Category": "Space Opera & Adventure"},
    {"Rank": 16, "Title": "Ex Machina", "Duration": "1h 48m", "Category": "AI & Ethics"},
    {"Rank": 17, "Title": "Back to the Future", "Duration": "1h 56m", "Category": "Time Travel & Comedy"},
    {"Rank": 18, "Title": "Dune", "Duration": "2h 35m", "Category": "Space Opera & Politics"},
    {"Rank": 19, "Title": "The War of the Worlds", "Duration": "1h 25m", "Category": "Alien Invasion"},
    {"Rank": 20, "Title": "Minority Report", "Duration": "2h 25m", "Category": "AI & Crime"},
    {"Rank": 21, "Title": "Children of Men", "Duration": "1h 49m", "Category": "Dystopia & Survival"},
    {"Rank": 22, "Title": "Avatar", "Duration": "2h 42m", "Category": "Alien & Environment"},
    {"Rank": 23, "Title": "Her", "Duration": "2h 6m", "Category": "AI & Relationships"},
    {"Rank": 24, "Title": "Gattaca", "Duration": "1h 46m", "Category": "Genetics & Society"},
    {"Rank": 25, "Title": "The Thing", "Duration": "1h 49m", "Category": "Alien & Horror"},
    {"Rank": 26, "Title": "Snowpiercer", "Duration": "2h 6m", "Category": "Dystopia & Survival"},
    {"Rank": 27, "Title": "Wall-E", "Duration": "1h 38m", "Category": "AI & Environment"},
    {"Rank": 28, "Title": "A.I. Artificial Intelligence", "Duration": "2h 26m", "Category": "AI & Emotions"},
    {"Rank": 29, "Title": "Annihilation", "Duration": "1h 55m", "Category": "Alien & Psychology"},
    {"Rank": 30, "Title": "The Prestige", "Duration": "2h 10m", "Category": "Science & Mystery"}
]

romantic = [
    {"Rank": 1, "Title": "Titanic", "Duration": "3h 14m", "Category": "Historical & Tragedy"},
    {"Rank": 2, "Title": "The Notebook", "Duration": "2h 3m", "Category": "Drama & Romance"},
    {"Rank": 3, "Title": "Pride and Prejudice", "Duration": "2h 9m", "Category": "Period & Romance"},
    {"Rank": 4, "Title": "La La Land", "Duration": "2h 8m", "Category": "Musical & Drama"},
    {"Rank": 5, "Title": "Casablanca", "Duration": "1h 42m", "Category": "Drama & War Romance"},
    {"Rank": 6, "Title": "Pretty Woman", "Duration": "1h 59m", "Category": "Rom-Com & Drama"},
    {"Rank": 7, "Title": "When Harry Met Sally", "Duration": "1h 35m", "Category": "Rom-Com & Friendship"},
    {"Rank": 8, "Title": "Eternal Sunshine of the Spotless Mind", "Duration": "1h 48m", "Category": "Drama & Sci-Fi Romance"},
    {"Rank": 9, "Title": "A Walk to Remember", "Duration": "1h 41m", "Category": "Drama & Tragedy"},
    {"Rank": 10, "Title": "The Fault in Our Stars", "Duration": "2h 6m", "Category": "Drama & Tragedy"},
    {"Rank": 11, "Title": "Notting Hill", "Duration": "2h 4m", "Category": "Rom-Com & Celebrity"},
    {"Rank": 12, "Title": "Romeo + Juliet", "Duration": "2h", "Category": "Drama & Tragedy"},
    {"Rank": 13, "Title": "The Princess Bride", "Duration": "1h 38m", "Category": "Fantasy & Comedy Romance"},
    {"Rank": 14, "Title": "Love Actually", "Duration": "2h 15m", "Category": "Rom-Com & Holiday"},
    {"Rank": 15, "Title": "10 Things I Hate About You", "Duration": "1h 37m", "Category": "Teen & Romance"},
    {"Rank": 16, "Title": "Silver Linings Playbook", "Duration": "2h 2m", "Category": "Drama & Mental Health"},
    {"Rank": 17, "Title": "To All the Boys I've Loved Before", "Duration": "1h 39m", "Category": "Teen & Rom-Com"},
    {"Rank": 18, "Title": "The Great Gatsby", "Duration": "2h 23m", "Category": "Drama & Period Romance"},
    {"Rank": 19, "Title": "Moulin Rouge!", "Duration": "2h 7m", "Category": "Musical & Tragedy"},
    {"Rank": 20, "Title": "Me Before You", "Duration": "1h 50m", "Category": "Drama & Tragedy"},
    {"Rank": 21, "Title": "Before Sunrise", "Duration": "1h 41m", "Category": "Drama & Conversation Romance"},
    {"Rank": 22, "Title": "Crazy, Stupid, Love.", "Duration": "1h 58m", "Category": "Rom-Com & Family"},
    {"Rank": 23, "Title": "The Holiday", "Duration": "2h 16m", "Category": "Rom-Com & Holiday"},
    {"Rank": 24, "Title": "50 First Dates", "Duration": "1h 39m", "Category": "Rom-Com & Memory"},
    {"Rank": 25, "Title": "Carol", "Duration": "1h 58m", "Category": "Drama & LGBTQ+ Romance"},
    {"Rank": 26, "Title": "Brokeback Mountain", "Duration": "2h 14m", "Category": "Drama & LGBTQ+ Romance"},
    {"Rank": 27, "Title": "Dear John", "Duration": "1h 48m", "Category": "Drama & Long-Distance Love"},
    {"Rank": 28, "Title": "The Vow", "Duration": "1h 44m", "Category": "Drama & Memory Loss"},
    {"Rank": 29, "Title": "Twilight", "Duration": "2h 2m", "Category": "Fantasy & Teen Romance"},
    {"Rank": 30, "Title": "My Best Friend's Wedding", "Duration": "1h 45m", "Category": "Rom-Com & Friendship"}
]

comedy = [
    {"Rank": 1, "Title": "Airplane!", "Duration": "1h 28m", "Category": "Parody & Satire"},
    {"Rank": 2, "Title": "Monty Python and the Holy Grail", "Duration": "1h 31m", "Category": "Parody & Adventure"},
    {"Rank": 3, "Title": "Superbad", "Duration": "1h 53m", "Category": "Teen & Friendship"},
    {"Rank": 4, "Title": "The Big Lebowski", "Duration": "1h 57m", "Category": "Crime & Absurd Comedy"},
    {"Rank": 5, "Title": "Groundhog Day", "Duration": "1h 41m", "Category": "Fantasy & Romance"},
    {"Rank": 6, "Title": "Anchorman: The Legend of Ron Burgundy", "Duration": "1h 34m", "Category": "Satire & Workplace"},
    {"Rank": 7, "Title": "Borat", "Duration": "1h 24m", "Category": "Mockumentary & Satire"},
    {"Rank": 8, "Title": "Dumb and Dumber", "Duration": "1h 47m", "Category": "Slapstick & Road Trip"},
    {"Rank": 9, "Title": "Caddyshack", "Duration": "1h 38m", "Category": "Sports & Slapstick"},
    {"Rank": 10, "Title": "Ferris Bueller's Day Off", "Duration": "1h 43m", "Category": "Teen & Adventure"},
    {"Rank": 11, "Title": "Hot Fuzz", "Duration": "2h 1m", "Category": "Action & Parody"},
    {"Rank": 12, "Title": "Ghostbusters", "Duration": "1h 45m", "Category": "Fantasy & Action Comedy"},
    {"Rank": 13, "Title": "Shaun of the Dead", "Duration": "1h 39m", "Category": "Zombie & Parody"},
    {"Rank": 14, "Title": "Bridesmaids", "Duration": "2h 5m", "Category": "Wedding & Friendship"},
    {"Rank": 15, "Title": "Step Brothers", "Duration": "1h 38m", "Category": "Family & Slapstick"},
    {"Rank": 16, "Title": "The Hangover", "Duration": "1h 40m", "Category": "Party & Mystery"},
    {"Rank": 17, "Title": "Office Space", "Duration": "1h 29m", "Category": "Workplace & Satire"},
    {"Rank": 18, "Title": "Tropic Thunder", "Duration": "1h 47m", "Category": "Action & Parody"},
    {"Rank": 19, "Title": "Napoleon Dynamite", "Duration": "1h 36m", "Category": "Quirky & Teen"},
    {"Rank": 20, "Title": "Some Like It Hot", "Duration": "2h 1m", "Category": "Romance & Cross-Dressing Comedy"},
    {"Rank": 21, "Title": "The Grand Budapest Hotel", "Duration": "1h 39m", "Category": "Dark Comedy & Adventure"},
    {"Rank": 22, "Title": "Mean Girls", "Duration": "1h 37m", "Category": "Teen & High School"},
    {"Rank": 23, "Title": "Zombieland", "Duration": "1h 28m", "Category": "Zombie & Adventure"},
    {"Rank": 24, "Title": "Dr. Strangelove", "Duration": "1h 35m", "Category": "Political & Satire"},
    {"Rank": 25, "Title": "The 40-Year-Old Virgin", "Duration": "1h 56m", "Category": "Romance & Comedy"},
    {"Rank": 26, "Title": "This Is Spinal Tap", "Duration": "1h 22m", "Category": "Mockumentary & Music"},
    {"Rank": 27, "Title": "Forgetting Sarah Marshall", "Duration": "1h 51m", "Category": "Breakup & Romance"},
    {"Rank": 28, "Title": "Planes, Trains and Automobiles", "Duration": "1h 33m", "Category": "Road Trip & Buddy Comedy"},
    {"Rank": 29, "Title": "The Truman Show", "Duration": "1h 43m", "Category": "Dark Comedy & Sci-Fi"},
    {"Rank": 30, "Title": "Big", "Duration": "1h 44m", "Category": "Fantasy & Family"}
]

ancient_history_movies = [
    {"Rank": 1, "Title": "Gladiator", "Duration": "2h 35m", "Category": "Ancient Rome & Action"},
    {"Rank": 2, "Title": "Braveheart", "Duration": "2h 58m", "Category": "Medieval Scotland & Drama"},
    {"Rank": 3, "Title": "Troy", "Duration": "2h 43m", "Category": "Ancient Greece & War"},
    {"Rank": 4, "Title": "300", "Duration": "1h 57m", "Category": "Ancient Greece & Battle"},
    {"Rank": 5, "Title": "Spartacus", "Duration": "3h 17m", "Category": "Ancient Rome & Rebellion"},
    {"Rank": 6, "Title": "The Ten Commandments", "Duration": "3h 40m", "Category": "Biblical & Drama"},
    {"Rank": 7, "Title": "Ben-Hur", "Duration": "3h 32m", "Category": "Ancient Rome & Revenge"},
    {"Rank": 8, "Title": "Cleopatra", "Duration": "4h 3m", "Category": "Ancient Egypt & Drama"},
    {"Rank": 9, "Title": "Apocalypto", "Duration": "2h 18m", "Category": "Mayan Civilization & Adventure"},
    {"Rank": 10, "Title": "Kingdom of Heaven", "Duration": "2h 24m", "Category": "Medieval Crusades & Drama"},
    {"Rank": 11, "Title": "The Passion of the Christ", "Duration": "2h 7m", "Category": "Biblical & Drama"},
    {"Rank": 12, "Title": "Alexander", "Duration": "2h 55m", "Category": "Ancient Greece & Biography"},
    {"Rank": 13, "Title": "The Last Samurai", "Duration": "2h 34m", "Category": "19th Century Japan & War"},
    {"Rank": 14, "Title": "Agora", "Duration": "2h 7m", "Category": "Ancient Alexandria & Philosophy"},
    {"Rank": 15, "Title": "Exodus: Gods and Kings", "Duration": "2h 30m", "Category": "Biblical & Drama"},
    {"Rank": 16, "Title": "The Eagle", "Duration": "1h 54m", "Category": "Ancient Rome & Adventure"},
    {"Rank": 17, "Title": "Pompeii", "Duration": "1h 45m", "Category": "Ancient Rome & Disaster"},
    {"Rank": 18, "Title": "The Northman", "Duration": "2h 17m", "Category": "Vikings & Revenge"},
    {"Rank": 19, "Title": "Outlaw King", "Duration": "2h 1m", "Category": "Medieval Scotland & War"},
    {"Rank": 20, "Title": "Robin Hood", "Duration": "2h 20m", "Category": "Medieval England & Adventure"},
    {"Rank": 21, "Title": "Red Cliff", "Duration": "2h 26m", "Category": "Ancient China & War"},
    {"Rank": 22, "Title": "Mongol: The Rise of Genghis Khan", "Duration": "2h 6m", "Category": "Mongolia & Biography"},
    {"Rank": 23, "Title": "Lawrence of Arabia", "Duration": "3h 36m", "Category": "20th Century & Adventure"},
    {"Rank": 24, "Title": "The Gladiator", "Duration": "1h 43m", "Category": "Ancient Rome & Arena Battles"},
    {"Rank": 25, "Title": "Joan of Arc", "Duration": "2h 40m", "Category": "Medieval France & Biography"},
    {"Rank": 26, "Title": "Risen", "Duration": "1h 47m", "Category": "Biblical & Mystery"},
    {"Rank": 27, "Title": "Centurion", "Duration": "1h 37m", "Category": "Ancient Rome & Survival"},
    {"Rank": 28, "Title": "The Man Who Would Be King", "Duration": "2h 9m", "Category": "19th Century & Adventure"},
    {"Rank": 29, "Title": "13 Assassins", "Duration": "2h 21m", "Category": "Feudal Japan & Action"},
    {"Rank": 30, "Title": "Quo Vadis", "Duration": "2h 51m", "Category": "Ancient Rome & Religion"}
]


futuristic_movies = [
    {"Rank": 1, "Title": "Blade Runner 2049", "Duration": "2h 44m", "Category": "Cyberpunk & AI"},
    {"Rank": 2, "Title": "The Matrix", "Duration": "2h 16m", "Category": "Virtual Reality & AI"},
    {"Rank": 3, "Title": "Inception", "Duration": "2h 28m", "Category": "Dreams & Technology"},
    {"Rank": 4, "Title": "Interstellar", "Duration": "2h 49m", "Category": "Space Exploration & Time"},
    {"Rank": 5, "Title": "Dune", "Duration": "2h 35m", "Category": "Space Opera & Politics"},
    {"Rank": 6, "Title": "Minority Report", "Duration": "2h 25m", "Category": "Crime & Precognition"},
    {"Rank": 7, "Title": "Gattaca", "Duration": "1h 46m", "Category": "Genetics & Dystopia"},
    {"Rank": 8, "Title": "Ex Machina", "Duration": "1h 48m", "Category": "AI & Ethics"},
    {"Rank": 9, "Title": "Elysium", "Duration": "1h 49m", "Category": "Class Divide & Space"},
    {"Rank": 10, "Title": "The Fifth Element", "Duration": "2h 6m", "Category": "Space Opera & Comedy"},
    {"Rank": 11, "Title": "Her", "Duration": "2h 6m", "Category": "AI & Romance"},
    {"Rank": 12, "Title": "RoboCop", "Duration": "1h 42m", "Category": "Crime & AI"},
    {"Rank": 13, "Title": "Snowpiercer", "Duration": "2h 6m", "Category": "Post-Apocalypse & Class Divide"},
    {"Rank": 14, "Title": "I, Robot", "Duration": "1h 55m", "Category": "AI & Crime"},
    {"Rank": 15, "Title": "Total Recall", "Duration": "1h 53m", "Category": "Memory & Space"},
    {"Rank": 16, "Title": "A.I. Artificial Intelligence", "Duration": "2h 26m", "Category": "AI & Emotions"},
    {"Rank": 17, "Title": "Ready Player One", "Duration": "2h 20m", "Category": "Virtual Reality & Adventure"},
    {"Rank": 18, "Title": "Wall-E", "Duration": "1h 38m", "Category": "AI & Environmentalism"},
    {"Rank": 19, "Title": "Alita: Battle Angel", "Duration": "2h 2m", "Category": "Cyberpunk & Action"},
    {"Rank": 20, "Title": "Looper", "Duration": "1h 59m", "Category": "Time Travel & Crime"},
    {"Rank": 21, "Title": "Children of Men", "Duration": "1h 49m", "Category": "Dystopia & Survival"},
    {"Rank": 22, "Title": "Upgrade", "Duration": "1h 40m", "Category": "AI & Revenge"},
    {"Rank": 23, "Title": "The Hunger Games", "Duration": "2h 22m", "Category": "Dystopia & Survival"},
    {"Rank": 24, "Title": "Oblivion", "Duration": "2h 4m", "Category": "Post-Apocalypse & Mystery"},
    {"Rank": 25, "Title": "The Road", "Duration": "1h 51m", "Category": "Post-Apocalypse & Survival"},
    {"Rank": 26, "Title": "The Time Machine", "Duration": "1h 36m", "Category": "Time Travel & Adventure"},
    {"Rank": 27, "Title": "Cloud Atlas", "Duration": "2h 52m", "Category": "Sci-Fi & Reincarnation"},
    {"Rank": 28, "Title": "Pacific Rim", "Duration": "2h 11m", "Category": "Robots & Monsters"},
    {"Rank": 29, "Title": "The Terminator", "Duration": "1h 47m", "Category": "AI & Time Travel"},
    {"Rank": 30, "Title": "Moon", "Duration": "1h 37m", "Category": "Space & AI"}
]


top_movies = [
    {"Rank": 1, "Title": "The Shawshank Redemption", "Duration": "2h 22m", "Category": "Drama & Friendship"},
    {"Rank": 2, "Title": "The Godfather", "Duration": "2h 55m", "Category": "Crime & Family"},
    {"Rank": 3, "Title": "The Dark Knight", "Duration": "2h 32m", "Category": "Superhero & Crime"},
    {"Rank": 4, "Title": "The Godfather Part II", "Duration": "3h 22m", "Category": "Crime & Family"},
    {"Rank": 5, "Title": "12 Angry Men", "Duration": "1h 36m", "Category": "Drama & Justice"},
    {"Rank": 6, "Title": "Schindler's List", "Duration": "3h 15m", "Category": "Historical & Drama"},
    {"Rank": 7, "Title": "The Lord of the Rings: The Return of the King", "Duration": "3h 21m", "Category": "Fantasy & Adventure"},
    {"Rank": 8, "Title": "Pulp Fiction", "Duration": "2h 34m", "Category": "Crime & Comedy"},
    {"Rank": 9, "Title": "The Lord of the Rings: The Fellowship of the Ring", "Duration": "2h 58m", "Category": "Fantasy & Adventure"},
    {"Rank": 10, "Title": "Forrest Gump", "Duration": "2h 22m", "Category": "Drama & Romance"},
    {"Rank": 11, "Title": "Inception", "Duration": "2h 28m", "Category": "Sci-Fi & Dreams"},
    {"Rank": 12, "Title": "Fight Club", "Duration": "2h 19m", "Category": "Drama & Mystery"},
    {"Rank": 13, "Title": "The Lord of the Rings: The Two Towers", "Duration": "2h 59m", "Category": "Fantasy & Adventure"},
    {"Rank": 14, "Title": "The Matrix", "Duration": "2h 16m", "Category": "Sci-Fi & Action"},
    {"Rank": 15, "Title": "Goodfellas", "Duration": "2h 26m", "Category": "Crime & Biography"},
    {"Rank": 16, "Title": "One Flew Over the Cuckoo's Nest", "Duration": "2h 13m", "Category": "Drama & Psychology"},
    {"Rank": 17, "Title": "Se7en", "Duration": "2h 7m", "Category": "Crime & Thriller"},
    {"Rank": 18, "Title": "The Silence of the Lambs", "Duration": "1h 58m", "Category": "Crime & Thriller"},
    {"Rank": 19, "Title": "It's a Wonderful Life", "Duration": "2h 10m", "Category": "Drama & Family"},
    {"Rank": 20, "Title": "Saving Private Ryan", "Duration": "2h 49m", "Category": "War & Drama"},
    {"Rank": 21, "Title": "The Green Mile", "Duration": "3h 9m", "Category": "Drama & Fantasy"},
    {"Rank": 22, "Title": "Interstellar", "Duration": "2h 49m", "Category": "Sci-Fi & Space"},
    {"Rank": 23, "Title": "The Usual Suspects", "Duration": "1h 46m", "Category": "Mystery & Thriller"},
    {"Rank": 24, "Title": "Léon: The Professional", "Duration": "1h 50m", "Category": "Action & Drama"},
    {"Rank": 25, "Title": "The Lion King", "Duration": "1h 28m", "Category": "Animation & Adventure"},
    {"Rank": 26, "Title": "Gladiator", "Duration": "2h 35m", "Category": "Action & Historical"},
    {"Rank": 27, "Title": "The Departed", "Duration": "2h 31m", "Category": "Crime & Thriller"},
    {"Rank": 28, "Title": "Whiplash", "Duration": "1h 46m", "Category": "Drama & Music"},
    {"Rank": 29, "Title": "Parasite", "Duration": "2h 12m", "Category": "Thriller & Social"},
    {"Rank": 30, "Title": "The Prestige", "Duration": "2h 10m", "Category": "Mystery & Drama"}
]


mix_movies = [
    {"Rank": 1, "Title": "The Notebook", "Duration": "2h 3m", "Category": "Drama & Romance"},
    {"Rank": 2, "Title": "Pride and Prejudice", "Duration": "2h 9m", "Category": "Period & Romance"},
    {"Rank": 3, "Title": "Troy", "Duration": "2h 43m", "Category": "Ancient Greece & War"},
    {"Rank": 4, "Title": "Spartacus", "Duration": "3h 17m", "Category": "Ancient Rome & Rebellion"},
    {"Rank": 5, "Title": "The Ten Commandments", "Duration": "3h 40m", "Category": "Biblical & Drama"},
    {"Rank": 6, "Title": "Apocalypto", "Duration": "2h 18m", "Category": "Mayan Civilization & Adventure"},
    {"Rank": 7, "Title": "Kingdom of Heaven", "Duration": "2h 24m", "Category": "Medieval Crusades & Drama"},
    {"Rank": 8, "Title": "The Passion of the Christ", "Duration": "2h 7m", "Category": "Biblical & Drama"},
    {"Rank": 9, "Title": "Agora", "Duration": "2h 7m", "Category": "Ancient Alexandria & Philosophy"},
    {"Rank": 10, "Title": "Alexander", "Duration": "2h 55m", "Category": "Ancient Greece & Biography"},
    {"Rank": 11, "Title": "Braveheart", "Duration": "2h 58m", "Category": "Medieval Scotland & Drama"},
    {"Rank": 12, "Title": "300", "Duration": "1h 57m", "Category": "Ancient Greece & Battle"},
    {"Rank": 13, "Title": "Ben-Hur", "Duration": "3h 32m", "Category": "Ancient Rome & Revenge"},
    {"Rank": 14, "Title": "The Last Samurai", "Duration": "2h 34m", "Category": "19th Century Japan & War"},
    {"Rank": 15, "Title": "Exodus: Gods and Kings", "Duration": "2h 30m", "Category": "Biblical & Drama"},
    {"Rank": 16, "Title": "The Eagle", "Duration": "1h 54m", "Category": "Ancient Rome & Adventure"},
    {"Rank": 17, "Title": "Gladiator", "Duration": "2h 35m", "Category": "Ancient Rome & Action"},
    {"Rank": 18, "Title": "Robin Hood", "Duration": "2h 20m", "Category": "Medieval England & Adventure"},
    {"Rank": 19, "Title": "The Northman", "Duration": "2h 17m", "Category": "Vikings & Revenge"},
    {"Rank": 20, "Title": "Red Cliff", "Duration": "2h 26m", "Category": "Ancient China & War"},
    {"Rank": 21, "Title": "Outlaw King", "Duration": "2h 1m", "Category": "Medieval Scotland & War"},
    {"Rank": 22, "Title": "Pompeii", "Duration": "1h 45m", "Category": "Ancient Rome & Disaster"},
    {"Rank": 23, "Title": "Pretty Woman", "Duration": "1h 59m", "Category": "Rom-Com & Drama"},
    {"Rank": 24, "Title": "The Great Gatsby", "Duration": "2h 23m", "Category": "Drama & Period Romance"},
    {"Rank": 25, "Title": "The Fault in Our Stars", "Duration": "2h 6m", "Category": "Drama & Tragedy"},
    {"Rank": 26, "Title": "Crazy, Stupid, Love.", "Duration": "1h 58m", "Category": "Rom-Com & Family"},
    {"Rank": 27, "Title": "Casablanca", "Duration": "1h 42m", "Category": "Drama & War Romance"},
    {"Rank": 28, "Title": "Romeo + Juliet", "Duration": "2h", "Category": "Drama & Tragedy"},
    {"Rank": 29, "Title": "Brokeback Mountain", "Duration": "2h 14m", "Category": "Drama & LGBTQ+ Romance"},
    {"Rank": 30, "Title": "Dear John", "Duration": "1h 48m", "Category": "Drama & Long-Distance Love"}
]